name: Build and Publish to GitHub Packages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        cp .github/settings.xml ~/.m2/settings.xml

    - name: Build with Maven
      working-directory: ./DemoApp
      run: mvn clean install

    - name: Deploy to GitHub Packages
      working-directory: ./DemoApp
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
