name: Build and Publish to GitHub Packages

on: [push,workflow_dispatch]
    branches: [ master ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
      MAVEN_OPTS: "-Xmx1024m"

    steps:
    - name: Enable GitHub Actions Debug Logging
      run: |
        echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
        echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        cp .github/settings.xml ~/.m2/settings.xml

    - name: Build with Maven (Debug)
      working-directory: ./SampleApp
      run: mvn -X clean install

    - name: Deploy to GitHub Packages (Debug)
      working-directory: ./SampleApp
      run: mvn -X deploy
